// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmb37CtO9htw9fqLUnH7Kibx_WT4VPywo',
    appId: '1:143648262780:web:4254b0b790ab286c56d7f9',
    messagingSenderId: '143648262780',
    projectId: 'bmiapp-11549',
    authDomain: 'bmiapp-11549.firebaseapp.com',
    storageBucket: 'bmiapp-11549.appspot.com',
    measurementId: 'G-5NQLEYYTWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPLO7VjM2g6VEco9lxb_xHNip1wlld41g',
    appId: '1:143648262780:android:28e6b14f1d3fc87a56d7f9',
    messagingSenderId: '143648262780',
    projectId: 'bmiapp-11549',
    storageBucket: 'bmiapp-11549.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD19dH1YP3q6tebWVI9v4cS3UyLsa44bmg',
    appId: '1:143648262780:ios:f09e02384f4eaacf56d7f9',
    messagingSenderId: '143648262780',
    projectId: 'bmiapp-11549',
    storageBucket: 'bmiapp-11549.appspot.com',
    iosBundleId: 'com.example.bmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD19dH1YP3q6tebWVI9v4cS3UyLsa44bmg',
    appId: '1:143648262780:ios:f09e02384f4eaacf56d7f9',
    messagingSenderId: '143648262780',
    projectId: 'bmiapp-11549',
    storageBucket: 'bmiapp-11549.appspot.com',
    iosBundleId: 'com.example.bmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmb37CtO9htw9fqLUnH7Kibx_WT4VPywo',
    appId: '1:143648262780:web:d3aad93520e8a03d56d7f9',
    messagingSenderId: '143648262780',
    projectId: 'bmiapp-11549',
    authDomain: 'bmiapp-11549.firebaseapp.com',
    storageBucket: 'bmiapp-11549.appspot.com',
    measurementId: 'G-REML31S7MR',
  );

}